export const navigating = [
  {
    DisplayText: 'Best Sellers',
    Query: 'q=(altcategory:"Best Sellers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/best-sellers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Abrasives',
    Query:
      'q=(category:"Abrasives %26 Sanding" OR "Grinding Wheels %26 Discs" OR "Hard Sleeves" OR "Sandblasting Media" OR "Sandblasters" OR "Belts" OR "Sanding Discs" OR "Sanding Sheets")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/abrasives',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Abrasives & Sanding',
    Query: 'q=(category:"Abrasives %26 Sanding")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/abrasives-and-sanding',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Grinding Wheels & Discs',
    Query: 'q=(category:"Grinding Wheels %26 Discs")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/grinding-wheels-and-discs',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hard Sleeves',
    Query: 'q=(category:"Hard Sleeves")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hard-sleeves',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sanding Belts',
    Query: 'q=(category:"Belts")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sanding-belts',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sanding Rolls',
    Query: 'q=sanding rolls&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sanding-rolls',
    BannerImage: '',
    SearchTriggers: 'sanding rolls',
  },
  {
    DisplayText: 'Sanding Sheets',
    Query: 'q=(category:"Sanding Sheets")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sanding-sheets',
    BannerImage: '',
    SearchTriggers: '',
  },

  {
    DisplayText: 'Air Tools & Compressors',
    Query: 'q=(categoryhead:"Air Tools %26 Compressors")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/air-tools-and-compressors',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Air Accessories',
    Query: 'q=(category:"Air Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/air-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Air Compressors',
    Query: 'q=(category:"Air Compressors")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/air-compressors',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Air Hose Reels',
    Query: 'q=(category:"Hose Reels")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/air-hose-reels',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Air Hoses',
    Query: 'q=(category:"Air Hose")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/air-hoses',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Combo Kit Nailer/Staplers',
    Query: 'q=(category:"Combo Kit Nailer/Staplers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/combo-kit-nailer-and-staplers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Die Grinders',
    Query: 'q=(category:"Die Grinders")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/die-grinders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Filters & Regulators',
    Query: 'q=(category:"Filters %26 Regulators")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/filters-and-regulators',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Fittings & Couplers',
    Query: 'q=(category:"Fittings %26 Couplers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/fitting-and-couplers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Framing Coils',
    Query: 'q=(category:"Framing %26 Coil")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/framing-coils',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Impact Wrenches',
    Query: 'q=(category:"Impact Wrenches")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/impact-wrenches',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Miscellaneous Pneumatic Tools',
    Query: 'q=(category:"Miscellaneous Pneumatic Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-pneumatic-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Nail Guns',
    Query: 'q=(category:"Nail Guns")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/nail-guns',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Nailers & Staplers',
    Query: 'q=(category:"Nailers %26 Staplers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/nailers-and-staplers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Pneumatic Nails & Staples',
    Query: 'q=pneumatic nails %26 staples&sortBy=instock desc,brandcode asc',
    VirtualPath: '/pneumatic-nails-and-staples',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Pneumatic Tools',
    Query: 'q=(category:"Pneumatic Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/pneumatic-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sanders',
    Query: 'q=(category:"Sanders") AND (category:"Pneumatic Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/pneumatic-sanders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Spray Gun Accessories',
    Query: 'q=spray gun accessories&sortBy=instock desc,brandcode asc',
    VirtualPath: '/spray-gun-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Spray Guns',
    Query: 'q=spray guns&sortBy=instock desc,brandcode asc',
    VirtualPath: '/spray-guns',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sprayers',
    Query: 'q=sprayers&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sprayers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Staple Guns',
    Query: 'q=(category:"Staple Guns")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/staple-guns',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Carving',
    Query: 'q=carving&sortBy=instock desc,brandcode asc',
    VirtualPath: '/carving',
    BannerImage: '',
    SearchTriggers: 'carving',
  },
  {
    DisplayText: 'Clamps, Vises & Jigs',
    Query: 'q=(categoryhead:"Clamps, Vises %26 Jigs")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/clamps-vises-and-jigs',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bar Clamps',
    Query: 'q=(category:"Bar Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bar-clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bench Vises',
    Query: 'q=(category:"Bench Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bench-vises',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'C-Clamps',
    Query: 'q=(category:"C-Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/c-clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Clamps',
    Query: 'q=(category:"Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dovetail Jigs',
    Query: 'q=(category:"Dovetail Jigs")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dovetail-jigs',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drill Press Vises',
    Query: 'q=(category:"Drill Press Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drill-press-vises',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Jigs & Fixtures',
    Query: 'q=(category:"Jigs %26 Fixtures")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/jigs-and-fixtures',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Kreg Jig',
    Query: 'q=(category:"Kreg Jig")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/kreg-jig',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Milling Vises',
    Query: 'q=(category:"Milling Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/milling-vises',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Miscellaneous Jigs & Fixtures',
    Query: 'q=(category:"Miscellaneous Jigs %26 Fixtures")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-jigs-and-fixtures',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Parallel Clamps',
    Query: 'q=(category:"Parallel Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/parallel-clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Specialty Clamps',
    Query: 'q=(category:"Specialty Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/specialty-clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Straight Edge Clamps',
    Query: 'q=(category:"Straight Edge Clamps")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/straight-edge-clamps',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Vises',
    Query: 'q=(category:"Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/vises',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Wood Vises',
    Query: 'q=(category:"Wood Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/wood-vises',
    BannerImage: '',
    SearchTriggers: '',
  },

  {
    DisplayText: 'CNC',
    Query: 'q=(categoryhead:"CNC")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Lasers',
    Query: 'q=(categoryid:395001)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC-lasers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Lathes',
    Query: 'q=(category:"CNC Lathes")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC-lathes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Mills',
    Query: 'q=(category:"CNC Mills")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC-mills',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Routers',
    Query: 'q=(categoryid:390001)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC-routers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Router Accessories',
    Query: 'q=(category:"CNC Router Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cnc-router-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'CNC Accessories',
    Query: 'q=(category:"CNC Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/CNC-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },

  {
    DisplayText: 'Cutting Tools & Tooling',
    Query: 'q=(categoryhead:"Cutting Tools %26 Tooling")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cutting-tools-and-tooling',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Boring Bars',
    Query: 'q=(category:"Boring Bars")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/boring-bars',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Clamping Kits',
    Query: 'q=(category:"Clamping Kits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/clamping-kits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Collets',
    Query: 'q=(category:"Collets")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/collets',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Cutting Tools',
    Query: 'q=(category:"Cutting Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cutting-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dies',
    Query: 'q=(category:"Dies")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dies',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'End Mill Holders',
    Query: 'q=(category:"Milling Attachments")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/end-mill-holders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'End Mills',
    Query: 'q=(category:"End Mills")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/end-mills',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Inserts',
    Query: 'q=(category:"Inserts")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/inserts',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Lathe Centers',
    Query: 'q=(category:"Lathe Centers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/lathe-centers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Lathe Chucks',
    Query: 'q=((category:"Metal Chucks") OR (category:"Wood Chucks"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/lathe-chucks',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Live Centers',
    Query: 'q=("Live Center")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/live-centers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Milling Vises',
    Query: 'q=(category:"Milling Vises")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/milling-vises',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rotary Burrs',
    Query: 'q=(category:"Rotary Burrs")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rotary-burrs',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rotary Tables',
    Query: 'q=(category:"Rotary Tables")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rotary-tables',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Slitting Saws',
    Query: 'q=(category:"Slitting Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/slitting-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Spiral Cutterheads',
    Query: 'q=(category:Cutterheads) AND (Spiral)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/spiral-cutterheads',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tap & Die Sets',
    Query: 'q=(category:"Tap %26 Die Sets")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tap-and-die-sets',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tooling',
    Query: 'q=(category:"Tooling")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tooling',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drilling & Boring',
    Query: 'q=(categoryhead:"Drilling %26 Boring")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drilling-and-boring',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Auger Bits',
    Query: 'q=(category:"Auger Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/auger-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Countersinks',
    Query: 'q=(category:"Countersinks")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/countersinks',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drill Bits',
    Query: 'q=(category:"Drill Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drill-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drill Chucks & Arbors',
    Query: 'q=((category:"Drill Chucks") OR (category:Arbors))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drill-chucks-and-arbors',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Forstner Bits',
    Query: 'q=(category:"Forstner Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/forstner-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hammer Drills',
    Query: 'q=("Hammer Drill")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hammer-drills',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hole Saws',
    Query: 'q=("Hole Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hole-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Lumberjack Cutters',
    Query: 'q=(cutter) AND (brand:"Lumberjack Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/lumberjack-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Power Bits',
    Query: 'q=(category:"Power Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/power-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Reamers',
    Query: 'q=(category:"Reamers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/reamers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Spade Bits',
    Query: 'q=(category:"Spade Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/spade-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tenon Cutters',
    Query: 'q=(category:"Plug/Tenon Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tenon-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Gunsmithing & Shooting',
    Query: 'q=(categoryhead:"Gunsmithing %26 Shooting")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/gunsmithing-and-shooting',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Chambering Reamers',
    Query: 'q=(category:"Gun Reamers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/chambering-reamers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Go/No Go Gauges',
    Query: 'q=(category:"Go No Go Gauges")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/go-and-no-go-gauges',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Gun Safes',
    Query: 'q=(category:"Gun Safes %26 Storage")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/gun-safes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Gunsmithing & Shooting',
    Query: 'q=(category:"Gunsmithing %26 Shooting")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/gunsmithing-and-shooting',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hearing Protection',
    Query: 'q=(category:"Hearing Protection")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hearing-protection',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Miscellaneous Gunsmithing Accessories',
    Query: 'q=(category:"Miscellaneous Gunsmithing Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-gunsmithing-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rifle Barrels',
    Query: 'q=(category:"Rifle Barrels")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rifle-barrels',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Shooting Accessories',
    Query: 'q=(bald AND eagle) OR (bald OR eagle)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/shooting-accessories',
    BannerImage: '',
    SearchTriggers: 'bald eagle, shooting accessories',
  },
  {
    DisplayText: 'Hand Tools',
    Query:
      'q=(category:"Chisels %26 Gouges") OR (category:"Cutlery") OR (category:"Files") OR (category:"Hammers") OR (category:"Mallets") OR (category:"Planes") OR (category:Saws) OR (category:"Miscellaneous Hand Tools") OR (category:"Pliers") OR (category:"Snips") OR ("scissors") OR (("stone") AND (category:Sharpening))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hand-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Chisels and Gouges',
    Query: 'q=(category:"Chisels%20%26%20Gouges")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/chisels-and-gouges',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Cutlery',
    Query: 'q=(category:"Cutlery")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cutlery',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Files',
    Query: 'q=(category:"Files")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/files',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hammers & Mallets',
    Query: 'q=((category:"Hammers") OR (category:"Mallets"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hammers-and-mallets',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hand Planes',
    Query: 'q=(category:"Planes")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hand-planes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hand Saws',
    Query: 'q=(category:Saws)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hand-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Miscellaneous Hand Tools',
    Query: 'q=(category:"Miscellaneous Hand Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-hand-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Pliers & Snips',
    Query: 'q=((category:"Pliers") OR (category:"Snips"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/pliers-and-snips',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sharpening Stones',
    Query: 'q=("stone") AND (category:Sharpening)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sharpening-stones',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Home & Shop',
    Query: 'q=(categoryhead:"Home %26 Shop")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/home-and-shop',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Adhesives',
    Query: 'q=(category:"Adhesives")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/adhesives',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Automotive Equipment',
    Query: 'q=(category:"Automotive Equipment")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/automotive-equipment',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Books, Plans, & DVDs',
    Query: 'q=((category:Books) OR (category:Plans) OR (category:DVDs))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/books-plans-and-dvds',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Casters',
    Query: 'q=(category:"Casters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/casters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Contractor, Home & Shop',
    Query: 'q=(category:"Contractor, Home %26 Shop")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/contractor-home-and-shop',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Cutlery',
    Query: 'q=(category:"Cutlery")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cutlery',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Fasteners',
    Query: 'q=(category:"Fasteners")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/fasteners',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Finishing',
    Query: 'q=(category:"Finishing")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/finishing',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Gifts',
    Query: 'q=(category:"Gifts")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/gifts',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Luthier Supplies',
    Query: 'q=(category:"Luthier Supplies")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/luthier-supplies',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Material Handling',
    Query: 'q=(category:"Material Handling")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/material-handling',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Mobile Bases',
    Query: 'q=(category:"Mobile Bases")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/mobile-bases',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Pen Making',
    Query: 'q=(category:"Pen Making")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/pen-making',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Presses',
    Query: 'q=(category:"Presses")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/presses',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Router Tables',
    Query: 'q=(category:"Router Tables")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/router-tables',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Shop Accessories',
    Query: 'q=(category:"Shop Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/shop-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Wheels',
    Query: 'q=(category:"Wheels")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/wheels',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hardware',
    Query: 'q=(categoryhead:"Hardware")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hardware',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drawer Pulls',
    Query: 'q=(category:"Drawer Pulls")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drawer-pulls',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drawer Slides',
    Query: 'q=(category:"Drawer Slides")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drawer-slides',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hinges',
    Query: 'q=(category:Hinges)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hinges',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Miscellaneous Hardware',
    Query: 'q=(category:"Miscellaneous Hardware")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-hardware',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Shelf Supports',
    Query: 'q=(category:"Shelf Supports")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/shelf-supports',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Logging',
    Query: 'q=logging&sortBy=instock desc,brandcode asc',
    VirtualPath: '/logging',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Machinery',
    Query: 'q=(categoryhead:"Machinery")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/machinery',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bandsaws - Metalworking',
    Query:
      'q=((category:"Bandsaws - Metalworking - Vertical") OR (category:"Bandsaws - Metalworking - Horizontal"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/metalworking-bandsaws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bandsaws - Woodworking',
    Query: 'q=((category:"Bandsaws - Woodworking") OR (category:"Bandsaws - Resaw"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/woodworking-bandsaws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Boring Machines',
    Query: 'q=(category:"Boring Machines")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/boring-machines',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Combination Lathe-Mills',
    Query: 'q=(category:"Combination Lathe-Mills")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/combination-lathe-mills',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drill Presses',
    Query: 'q=(category:"Drill Presses")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drill-presses',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dust Collection Accessories',
    Query: 'q=(category:"Dust Collection Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dust-collection-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dust Collectors',
    Query: 'q=(category:"Dust Collectors")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dust-collectors',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Jointers',
    Query: 'q=(category:"Jointers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/jointers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Lathes - Metalworking',
    Query: 'q=(category:"Metal Lathes")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/metal-lathes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Lathes - Woodworking',
    Query: 'q=(category:"Wood Lathes")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/wood-lathes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Machine Accessories',
    Query: 'q=(category:"Machine Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/machine-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Metalworking Machines - Misc',
    Query: 'q=(category:"Metalworking Machines-Misc")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/metalworking-machines-misc',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Milling Machines',
    Query: 'q=(category:"Milling Machines")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/milling-machines',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Motors, Switches, & Electrical',
    Query: 'q=(category:"Motors, Switches %26 Electrical")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/motors-switches-and-electrical',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Planers',
    Query: 'q=(category:"Planers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/planers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sanders',
    Query: 'q=(category:"Sanders")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sanders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Shapers',
    Query: 'q=(category:"Shapers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/shapers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sheet Metal Machines',
    Query: 'q=(category:"Sheet Metal Machines")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sheet-metal-machines',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Surface Grinders',
    Query: 'q=(category:"Surface Grinders")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/surface-grinders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Table Saws',
    Query: 'q=(category:"Table Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tablesaws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Woodworking Machines - Misc',
    Query: 'q=(category:"Woodworking Machines-Misc")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/woodworking-machines-misc',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Measuring',
    Query: 'q=(categoryhead:"Measuring")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/measuring',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Calipers',
    Query: 'q=(category:"Calipers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/calipers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'DROs',
    Query: 'q=(category:"Digital Read-Outs")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dros',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dial Gauges & Indicators',
    Query: 'q=(gauge OR indicator) AND (category:"Measuring Instruments")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dial-gauges-and-indicators',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Granite Plates & Stands',
    Query: 'q=(granite) AND (category:"Measuring Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/granite-plates-and-stands',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Magnetic Bases',
    Query: 'q=(magnetic OR base) AND (category:"Measuring Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/magnetic-bases',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Measuring Tools',
    Query: 'q=(category:"Measuring Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/measuring-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Measuring Instruments',
    Query: 'q=(category:"Measuring Instruments")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/measuring-instruments',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Micrometers',
    Query: 'q=(category:"Micrometers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/micrometers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rules & Squares',
    Query: 'q=((category:Rules) OR (category:Squares))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rules-and-squares',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Power Tools',
    Query: 'q=(categoryhead:"Power Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/power-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Batteries & Chargers',
    Query: 'q=(category:"Batteries %26 Chargers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/batteries-and-chargers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Circular Saws',
    Query: 'q=(category:"Circular Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/circular-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Cordless Tools',
    Query: 'q=(cordless) AND (category:"Power Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cordless-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Cut Off Saws',
    Query: 'q=(category:"Cut-Off Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/cut-off-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Drills',
    Query: 'q=(category:"Drills")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/drills',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Heat Guns',
    Query: 'q=("Heat Gun")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/heat-guns',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Jig Saws',
    Query: 'q=(category:"Jig Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/jig-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Multi-Tools Accessories',
    Query: 'q=(category:"Multitools Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/multitools-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Oscillating Multi-Tools',
    Query: 'q=(category:"Oscillating Multi-Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/oscillating-multi-tools',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Power Tool Accessories',
    Query: 'q=(category:"Power Tool Accessories")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/power-tool-accessories',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Reciprocating Saws',
    Query: 'q=(category:"Reciprocating Saws")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/reciprocating-saws',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Routers',
    Query: 'q=(category:"Routers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/routers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sanders',
    Query: 'q=(category:"Sanders") AND (category:"Power Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sanders',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Router Bits & Shaper Cutters',
    Query: 'q=(altcategory:"Router Bits and Shaper Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/router-bits-and-shaper-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bead & Flute Cutters',
    Query: 'q=(category:"Bead %26 Flute Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bead-and-flute-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bull Nose Bits',
    Query: 'q=(category:"Bull Nose Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bull-nose-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bushings & Spacers',
    Query: 'q=(category:"Bushings %26 Spacers")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bushings-and-spacers',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dovetail Cutters',
    Query: 'q=(category:"Dovetail Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dovetail-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Ogee Cutters',
    Query: 'q=(ogee) AND (category:"Shaper Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/ogee-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Plunge Bits',
    Query: 'q=(category:"Plunge Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/plunge-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Profile Knives',
    Query: 'q=(category:"Profile Knives")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/profile-knives',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rabbeting Cutters',
    Query: 'q=(category:"Rabbeting Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rabbeting-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Raised Panel Cutter',
    Query: 'q=(category:"Raised Panel Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/raised-panel-cutter',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rosette Cutters',
    Query: 'q=(category:"Rosette Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rosette-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Roundover Bits',
    Query: 'q=(category:"Roundover Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/roundover-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Router Bits',
    Query: 'q=(category:"Router Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/router-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Router Bit Sets',
    Query: 'q=(category:"Router Bit Sets")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/router-bit-sets',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Rub Collars',
    Query: 'q=(category:"Rub Collars")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/rub-collars',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Shaper Cutters',
    Query: 'q=(category:"Shaper Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/shaper-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Specialty Cutters',
    Query: 'q=(category:"Specialty Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/specialty-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Spiral Cutterheads',
    Query: 'q=(spiral) AND (category:Cutterheads)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/spiral-cutterheads',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Stile & Rail Cutters',
    Query: 'q=(category:"Stile %26 Rail Cutters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/stile-and-rail-cutters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Straight Bits',
    Query: 'q=(category:"Straight Bits")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/straight-bits',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tongue & Groove',
    Query:
      'q=((category:"Tongue %26 Groove Bits") OR (category:"Tongue %26 Groove Cutters"))&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tongue-and-groove',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sandblasting',
    Query: 'q=sandblasting&sortBy=instock desc,brandcode asc',
    VirtualPath: '/Sandblasting',
    BannerImage: '',
    SearchTriggers: 'sandblasting',
  },
  {
    DisplayText: 'Sand for Sandblasters',
    Query: 'q=(category:"Sandblasting Media")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sand-for-sandblasters',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Sandblasters',
    Query: 'q=(category:"Sandblasters")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/sandblasters',
    BannerImage: '',
    SearchTriggers: 'sandblasters',
  },
  {
    DisplayText: 'Safety / PPE',
    Query: 'q=(categoryhead:"Safety %26 ppe")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/safety-and-ppe',
    BannerImage: '',
    SearchTriggers: 'ppe, safety',
  },
  {
    DisplayText: 'Eye Protection',
    Query: 'q=(category:"Eye Protection")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/eye-protection',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Gloves',
    Query: 'q=(category:"Gloves")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/gloves',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Hearing Protection',
    Query: 'q=(category:"Hearing Protection")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/hearing-protection',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Respirators',
    Query: 'q=(category:"Respirators")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/respirators',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Safety Equipment',
    Query: 'q=(category:"Safety Equipment")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/safety-equipment',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Security Equipment',
    Query: 'q=(category:"Security Equipment")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/security-equipment',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Saw Blades',
    Query: 'q=(categoryhead:"Saw Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/saw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Bandsaw Blades',
    Query: 'q=(category:"Bandsaw Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/bandsaw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Circular Saw Blades',
    Query: 'q=(category:"Circular Saw Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/circular-saw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Dado Blades',
    Query: 'q=(category:"Dado Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/dado-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Freud',
    Query: 'q=(brand:"Freud")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/freud',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Forrest',
    Query: 'q=(brand:"Forrest")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/forrest',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Inserts for Spiral Cutterheads',
    Query: 'q=(category:Inserts)&sortBy=instock desc,brandcode asc',
    VirtualPath: '/inserts-for-spiral-cutterheads',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Oscillating Saw Blades',
    Query: 'q=(blade) AND (category:"Oscillating Multi-Tools")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/oscillating-saw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Jigsaw Blades',
    Query: 'q=(category:"Jigsaw Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/jigsaw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Reciprocating Blades',
    Query: 'q=(category:"Reciprocating Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/reciprocating-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tablesaw Blades',
    Query: 'q=(category:"Circular Saw Blades")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/circular-saw-blades',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tool Storage & Workbenches',
    Query: 'q=tool storage OR workbenches&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tool-storage-and-workbenches',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tool Boxes',
    Query: 'q=(category:"Tool Boxes")&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tool-boxes',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Tool Storage',
    Query: 'q=tool storage&sortBy=instock desc,brandcode asc',
    VirtualPath: '/tool-storage',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Workbenches',
    Query: 'q=workbench&sortBy=instock desc,brandcode asc',
    VirtualPath: '/workbenches',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Welding',
    Query: 'q=welding OR welders&sortBy=instock desc,brandcode asc',
    VirtualPath: '/welding',
    BannerImage: '',
    SearchTriggers: 'welding',
  },
  {
    DisplayText: 'Miscellaneous Welding & Cutting',
    Query: 'q=miscellaneous welding %26 cutting&sortBy=instock desc,brandcode asc',
    VirtualPath: '/miscellaneous-welding-and-cutting',
    BannerImage: '',
    SearchTriggers: '',
  },
  {
    DisplayText: 'Welders',
    Query: 'q=welders&sortBy=instock desc,brandcode asc',
    VirtualPath: '/welders',
    BannerImage: '',
    SearchTriggers: 'welders',
  },
  {
    DisplayText: 'Welding Carts',
    Query: 'q=welding cart&sortBy=instock desc,brandcode asc',
    VirtualPath: '/welding-carts',
    BannerImage: '',
    SearchTriggers: 'welding cart, welding carts',
  },
  {
    DisplayText: 'Welding Table Accessories',
    Query: 'q=welding table accessories&sortBy=instock desc,brandcode asc',
    VirtualPath: '/welding-table-accessories',
    BannerImage: '',
    SearchTriggers: 'welding table accessories',
  },
  {
    DisplayText: 'Welding Tables',
    Query: 'q=welding tables&sortBy=instock desc,brandcode asc',
    VirtualPath: '/welding-tables',
    BannerImage: '',
    SearchTriggers: 'welding tables',
  },
];
